"""Directly insert expanded jobs and candidates into the database."""
import sys, os
os.chdir(os.path.dirname(__file__))
sys.path.insert(0, ".")

from app.database import init_db, SessionLocal, JobPosting, Candidate, Skill

init_db()

NEW_JOBS = [
    # ── FINANCE ──────────────────────────────────────────────────────────────
    {"title": "Financial Analyst", "description": "We are looking for a detail-oriented Financial Analyst to join our corporate finance team. You will build financial models, analyze investment opportunities, support budgeting and forecasting processes, and prepare management reporting packages. Strong proficiency in Excel, financial modeling, and accounting principles (GAAP/IFRS) is required. Experience with Bloomberg or Refinitiv preferred. CFA candidate or holder is a plus.", "required_skills": ["financial modeling", "financial analysis", "excel", "sql", "budgeting", "forecasting", "gaap", "bloomberg"], "min_experience": 2.0, "education_level": "Bachelor"},
    {"title": "Senior Risk Manager", "description": "We seek an experienced Risk Manager to oversee enterprise risk frameworks covering credit risk, market risk, and operational risk. You will conduct VaR analysis, stress testing, and regulatory reporting (Basel III / Solvency II). Deep expertise in quantitative risk methodologies, Python or R for risk modelling, and regulatory frameworks is essential. FRM or CFA designation preferred.", "required_skills": ["risk management", "credit risk", "market risk", "var", "stress testing", "regulatory reporting", "python", "r", "basel iii", "frm"], "min_experience": 5.0, "education_level": "Master"},
    {"title": "Investment Banking Analyst", "description": "Join our M&A advisory team to support deal execution across sectors. Responsibilities include financial modeling, valuation (DCF, LBO, comparable company analysis), preparation of pitch books, and client due diligence. Candidates should be highly numerate, proficient in Excel and PowerPoint, with strong understanding of capital markets and corporate finance.", "required_skills": ["financial modeling", "valuation", "dcf", "lbo", "merger & acquisition", "excel", "powerpoint", "bloomberg", "financial analysis"], "min_experience": 1.0, "education_level": "Bachelor"},
    {"title": "Treasury & Cash Management Analyst", "description": "Manage daily cash positions, FX hedging programs, and short-term investment portfolios. You will maintain banking relationships, support treasury system implementation (SAP Treasury), ensure compliance with treasury policies, and prepare liquidity forecasts. Experience in fx hedging, cash management, and ERP systems required.", "required_skills": ["treasury management", "cash management", "fx hedging", "sap", "financial modeling", "excel", "forecasting"], "min_experience": 3.0, "education_level": "Bachelor"},
    {"title": "AML & Compliance Officer", "description": "Responsible for designing and implementing AML, KYC and regulatory compliance programs. You will conduct transaction monitoring, suspicious activity reporting, and regulatory liaison. Must have deep knowledge of AML regulations, FATF standards, and financial crime typologies.", "required_skills": ["aml", "kyc", "compliance", "regulatory compliance", "risk management", "financial analysis"], "min_experience": 3.0, "education_level": "Bachelor"},
    {"title": "Equity Research Analyst", "description": "Produce in-depth equity research reports, earnings models, and investment recommendations for institutional clients. You will build and maintain detailed financial models, participate in earnings calls, and monitor sector trends. CFA qualification and experience with Bloomberg Terminal and FactSet required.", "required_skills": ["equity research", "financial modeling", "valuation", "bloomberg", "investment analysis", "excel", "cfa", "financial reporting"], "min_experience": 2.0, "education_level": "Bachelor"},
    # ── HEALTHCARE ────────────────────────────────────────────────────────────
    {"title": "Clinical Data Analyst", "description": "Join our clinical research team to analyze clinical trial datasets, generate statistical outputs, and contribute to regulatory submissions. You will work with clinical data management systems (REDCap, Medidata Rave), apply biostatistical methods, and collaborate with clinical operations. Proficiency in SAS or R, understanding of ICH/GCP guidelines, and familiarity with FDA/EMA regulatory requirements is required.", "required_skills": ["clinical research", "clinical trials", "biostatistics", "r", "clinical data management", "redcap", "gcp", "fda regulations"], "min_experience": 2.0, "education_level": "Master"},
    {"title": "Healthcare IT Specialist", "description": "Implement, configure, and support healthcare information systems including EMR/EHR platforms (Epic, Cerner). You will lead HL7/FHIR integration projects, ensure HIPAA compliance, support clinical workflow optimization, and conduct end-user training.", "required_skills": ["emr", "ehr", "epic", "hl7", "fhir", "hipaa", "healthcare interoperability", "sql"], "min_experience": 3.0, "education_level": "Bachelor"},
    {"title": "Pharmacovigilance Specialist", "description": "Monitor drug safety signals, process adverse event reports, and prepare submissions to regulatory authorities (FDA MedWatch, EMA EudraVigilance). You will conduct literature searches, signal detection, and periodic safety update reports (PSURs). Strong knowledge of ICH E2 guidelines, GVP modules, and MedDRA coding required.", "required_skills": ["pharmacovigilance", "drug safety", "adverse event reporting", "fda regulations", "gcp", "medical writing", "regulatory submissions"], "min_experience": 2.0, "education_level": "Bachelor"},
    {"title": "Healthcare Data Scientist", "description": "Develop predictive models and real-world evidence studies using large healthcare datasets (claims, EHR, registries). Apply machine learning, survival analysis, and NLP to improve patient outcomes and operational efficiency. Experience with Python/R, healthcare data standards (HL7, FHIR, ICD-10), and regulatory/ethical considerations in healthcare AI required.", "required_skills": ["machine learning", "python", "r", "healthcare analytics", "hl7", "fhir", "icd-10", "nlp", "biostatistics", "real-world evidence"], "min_experience": 3.0, "education_level": "Master"},
    {"title": "Hospital Operations Manager", "description": "Oversee day-to-day hospital operations, coordinate clinical and non-clinical departments, and drive process improvement initiatives. You will manage budgets, staffing plans, patient flow, and accreditation requirements.", "required_skills": ["hospital administration", "healthcare operations", "project management", "lean manufacturing", "six sigma", "budgeting", "stakeholder management"], "min_experience": 5.0, "education_level": "Master"},
    # ── DIGITAL MARKETING ────────────────────────────────────────────────────
    {"title": "Digital Marketing Manager", "description": "Lead the digital marketing strategy across paid search, paid social, SEO, email, and display channels. You will manage campaign performance using Google Analytics 4, optimize ROI across Google Ads and Meta Ads, oversee marketing automation (HubSpot/Marketo), and collaborate with content and creative teams.", "required_skills": ["digital marketing", "seo", "sem", "google ads", "meta ads", "google analytics", "ga4", "hubspot", "email marketing", "a/b testing"], "min_experience": 4.0, "education_level": "Bachelor"},
    {"title": "SEO & Content Marketing Specialist", "description": "Develop and execute organic growth strategies through technical SEO audits, keyword research, link-building campaigns, and high-quality content production. You will use tools like Ahrefs, SEMrush, and Google Search Console to track rankings and traffic.", "required_skills": ["seo", "content marketing", "copywriting", "ahrefs", "semrush", "google analytics", "content strategy", "a/b testing"], "min_experience": 2.0, "education_level": "Bachelor"},
    {"title": "Performance Marketing Analyst", "description": "Manage and optimize paid media campaigns across Google Ads, Meta, LinkedIn, and programmatic channels. You will analyze campaign data, conduct A/B tests, build attribution models, and report on ROAS and CPA metrics.", "required_skills": ["performance marketing", "ppc", "google ads", "meta ads", "a/b testing", "google analytics", "sql", "tableau", "conversion rate optimization"], "min_experience": 2.0, "education_level": "Bachelor"},
    {"title": "Brand & Social Media Manager", "description": "Define and maintain brand identity across all touchpoints. You will manage organic and paid social media presence on Instagram, LinkedIn, TikTok, and YouTube; create content calendars; engage communities; and measure brand health metrics.", "required_skills": ["brand management", "social media marketing", "content marketing", "canva", "adobe creative suite", "community management", "copywriting", "influencer marketing"], "min_experience": 3.0, "education_level": "Bachelor"},
    {"title": "CRM & Marketing Automation Specialist", "description": "Build, automate, and optimize multi-touch customer journeys using HubSpot and Salesforce Marketing Cloud. You will segment audiences, design email nurture programs, manage lead scoring, and analyze lifecycle metrics.", "required_skills": ["crm", "hubspot", "email marketing", "marketing automation", "salesforce", "customer lifecycle", "sql", "a/b testing"], "min_experience": 2.0, "education_level": "Bachelor"},
    # ── LEGAL ────────────────────────────────────────────────────────────────
    {"title": "Corporate Legal Counsel", "description": "Provide legal advice across commercial contracts, corporate governance, M&A transactions, and regulatory compliance. You will draft and negotiate a wide range of agreements, advise the board on corporate matters, and manage external counsel.", "required_skills": ["corporate law", "contract drafting", "contract negotiation", "merger & acquisition", "legal research", "legal writing", "compliance", "due diligence"], "min_experience": 5.0, "education_level": "Master"},
    {"title": "Data Privacy & GDPR Specialist", "description": "Develop and maintain the company's data protection framework in compliance with GDPR, CCPA, and other applicable privacy laws. You will conduct DPIAs, maintain records of processing activities, handle data subject requests, and work with IT teams on privacy-by-design implementation.", "required_skills": ["data privacy", "gdpr", "ccpa", "regulatory compliance", "legal research", "legal writing", "compliance"], "min_experience": 3.0, "education_level": "Bachelor"},
    {"title": "IP & Technology Lawyer", "description": "Manage the company's intellectual property portfolio including patents, trademarks, and copyrights. You will advise on IP strategy, conduct freedom-to-operate analyses, manage licensing agreements, and support technology transactions.", "required_skills": ["intellectual property", "patent law", "trademark", "copyright", "contract drafting", "legal research", "licensing"], "min_experience": 4.0, "education_level": "Master"},
    # ── MECHANICAL / CIVIL / ELECTRICAL ENGINEERING ──────────────────────────
    {"title": "Senior Mechanical Design Engineer", "description": "Lead the mechanical design of industrial equipment and product assemblies using SolidWorks and CATIA. You will perform FEA simulations (ANSYS), GD&T tolerancing, design for manufacturability reviews, and collaborate with manufacturing teams.", "required_skills": ["solidworks", "catia", "finite element analysis", "ansys", "mechanical design", "autocad", "lean manufacturing", "fmea", "quality management"], "min_experience": 5.0, "education_level": "Bachelor"},
    {"title": "Civil & Structural Engineer", "description": "Design and analyze structural systems for commercial and infrastructure projects. You will prepare structural calculations, drawings in AutoCAD/Revit, and BIM models. Experience with ETABS, SAP2000, or STAAD.Pro for structural analysis, and knowledge of Eurocode / ACI standards required.", "required_skills": ["civil engineering", "structural analysis", "autocad", "revit", "bim", "construction management", "project scheduling"], "min_experience": 3.0, "education_level": "Bachelor"},
    {"title": "Electrical & Instrumentation Engineer", "description": "Design electrical systems, instrument loops, and control architecture for oil & gas and process industries. Responsibilities include P&ID development, cause-and-effect diagrams, PLC/DCS programming, and SCADA configuration.", "required_skills": ["electrical engineering", "plc programming", "scada", "instrumentation", "control systems", "autocad", "quality management"], "min_experience": 4.0, "education_level": "Bachelor"},
    {"title": "Manufacturing & Process Improvement Engineer", "description": "Drive Lean/Six Sigma initiatives to eliminate waste, reduce cycle times, and improve product quality across manufacturing lines. You will lead kaizen events, conduct time-motion studies, implement 5S programs, and use statistical process control (SPC) methods. Black Belt or Green Belt certification preferred.", "required_skills": ["lean manufacturing", "six sigma", "quality management", "fmea", "root cause analysis", "process improvement"], "min_experience": 3.0, "education_level": "Bachelor"},
    # ── HUMAN RESOURCES ──────────────────────────────────────────────────────
    {"title": "HR Business Partner", "description": "Act as a strategic advisor to business leaders, delivering talent solutions aligned with business objectives. You will manage performance cycles, drive organizational design, lead change management initiatives, resolve employee relations issues, and partner on workforce planning.", "required_skills": ["talent acquisition", "performance management", "employee relations", "change management", "hr analytics", "workday", "employment law", "organizational development"], "min_experience": 5.0, "education_level": "Bachelor"},
    {"title": "Talent Acquisition Manager", "description": "Lead full-cycle recruitment for senior and specialist roles across business functions. You will design sourcing strategies, manage Employer Value Proposition (EVP), use LinkedIn Recruiter and ATS platforms, develop hiring manager capability, and report on recruiting metrics.", "required_skills": ["talent acquisition", "recruitment", "linkedin recruiter", "sourcing", "hris", "hr analytics", "onboarding", "stakeholder management"], "min_experience": 4.0, "education_level": "Bachelor"},
    {"title": "Learning & Development Specialist", "description": "Design, develop, and facilitate learning programs aligned to business needs. You will apply instructional design methodologies (ADDIE, SAM), build e-learning content in Articulate Storyline and Rise, manage LMS platforms (Moodle, Cornerstone), and evaluate program effectiveness using Kirkpatrick model.", "required_skills": ["learning & development", "instructional design", "e-learning", "articulate storyline", "lms", "moodle", "training delivery", "content creation", "facilitation"], "min_experience": 3.0, "education_level": "Bachelor"},
    {"title": "Compensation & Benefits Analyst", "description": "Conduct market pay benchmarking, maintain job architecture and grading systems, design incentive compensation plans, and administer benefits programs. You will use compensation surveys, build Excel models for total rewards analysis, and partner with HR Business Partners on C&B strategy.", "required_skills": ["compensation & benefits", "hr analytics", "excel", "financial modeling", "workday", "hris"], "min_experience": 3.0, "education_level": "Bachelor"},
    # ── SUPPLY CHAIN ──────────────────────────────────────────────────────────
    {"title": "Supply Chain Analyst", "description": "Analyze supply chain data to identify cost reduction, inventory optimization, and service improvement opportunities. You will build demand forecasts, run S&OP processes, manage KPI dashboards, and support ERP data management (SAP SCM / Oracle).", "required_skills": ["supply chain management", "demand planning", "s&op", "inventory management", "sap scm", "sql", "excel", "data analysis"], "min_experience": 2.0, "education_level": "Bachelor"},
    {"title": "Procurement & Sourcing Manager", "description": "Lead strategic sourcing initiatives, manage supplier relationships, and negotiate contracts to deliver cost savings and supply security. You will conduct RFQ/RFP processes, supplier evaluation, and category management.", "required_skills": ["procurement", "strategic sourcing", "vendor management", "category management", "contract negotiation", "sap", "rfq", "supply chain management"], "min_experience": 5.0, "education_level": "Bachelor"},
    {"title": "Logistics & Distribution Manager", "description": "Manage end-to-end logistics operations including inbound, warehousing, order fulfillment, and last-mile delivery. You will oversee 3PL partnerships, manage transportation costs, ensure customs compliance (Incoterms), and implement warehouse management system (WMS) improvements.", "required_skills": ["logistics", "warehousing", "inventory management", "3pl", "import/export", "customs", "supply chain management", "vendor management"], "min_experience": 4.0, "education_level": "Bachelor"},
    # ── SALES ──────────────────────────────────────────────────────────────────
    {"title": "Enterprise Sales Manager", "description": "Drive new business revenue by leading a team of account executives targeting enterprise accounts. You will define territory strategies, coach sales reps, manage a complex B2B pipeline in Salesforce, and engage C-suite stakeholders.", "required_skills": ["b2b sales", "enterprise sales", "sales management", "salesforce", "pipeline management", "negotiation", "sales forecasting", "crm"], "min_experience": 6.0, "education_level": "Bachelor"},
    {"title": "Business Development Manager", "description": "Identify, qualify, and close strategic partnership and new revenue opportunities. You will develop go-to-market plans, conduct market research, build business cases, and manage stakeholder relationships.", "required_skills": ["business development", "b2b sales", "market research", "negotiation", "crm", "strategic planning", "stakeholder management", "salesforce"], "min_experience": 4.0, "education_level": "Bachelor"},
    {"title": "Customer Success Manager", "description": "Own the post-sales relationship for a portfolio of enterprise accounts, ensuring adoption, satisfaction, retention, and growth. You will conduct QBRs, build success plans, identify upsell opportunities, and act as the voice of the customer internally.", "required_skills": ["customer success", "account management", "salesforce", "crm", "upselling", "stakeholder management", "client relationship management"], "min_experience": 3.0, "education_level": "Bachelor"},
    # ── EDUCATION & TRAINING ──────────────────────────────────────────────────
    {"title": "Instructional Designer & E-Learning Developer", "description": "Design and develop engaging digital learning experiences for corporate audiences. You will apply the ADDIE and SAM models, create SCORM-compliant e-learning modules in Articulate Storyline and Rise, manage content in LMS platforms (Moodle, Cornerstone), and collaborate with SMEs to ensure accuracy and relevance.", "required_skills": ["instructional design", "e-learning", "articulate storyline", "scorm", "lms", "moodle", "curriculum development", "adult learning theory", "content creation"], "min_experience": 2.0, "education_level": "Bachelor"},
    {"title": "Corporate Training & Development Manager", "description": "Lead the company's learning strategy, manage the training team, and partner with HR and business leaders on capability building. You will design leadership development programs, manage vendor relationships, oversee the LMS, and measure training ROI using Kirkpatrick model.", "required_skills": ["training delivery", "learning & development", "instructional design", "lms", "facilitation", "coaching", "stakeholder management", "hr analytics"], "min_experience": 6.0, "education_level": "Master"},
]

NEW_CANDIDATES = [
    # ── FINANCE ──────────────────────────────────────────────────────────────
    {"name": "Sophie Laurent", "email": "sophie.laurent@email.com", "phone": "+1-212-555-0181", "education": "Master", "experience_years": 6.0, "skills": ["financial modeling", "financial analysis", "excel", "sql", "bloomberg", "valuation", "dcf", "equity research", "powerpoint", "financial reporting"], "raw_text": "Sophie Laurent\nsophie.laurent@email.com | +1-212-555-0181\nCFA charterholder with 6 years of equity research and investment banking experience.\nSenior Equity Research Analyst | Morgan Stanley | 06/2021 - Present\nBuild DCF, LBO, and comparable company analysis models for technology sector coverage.\nPublish initiation reports using Bloomberg Terminal and FactSet.\nInvestment Banking Analyst | Goldman Sachs | 07/2018 - 05/2021\nExecuted 12+ M&A advisory mandates with aggregate deal value of $4.2B.\nMaster of Finance | Columbia Business School | 2018\nBachelor of Economics | New York University | 2016\nSkills: Financial Modeling, Financial Analysis, Valuation, DCF, LBO, Equity Research, Bloomberg, Excel, SQL, PowerPoint, Financial Reporting, Merger & Acquisition, CFA"},
    {"name": "Marcus Webb", "email": "marcus.webb@email.com", "phone": "+44-20-555-0182", "education": "Master", "experience_years": 8.0, "skills": ["risk management", "credit risk", "market risk", "var", "stress testing", "regulatory reporting", "python", "r", "basel iii", "financial modeling", "sql"], "raw_text": "Marcus Webb\nmarcus.webb@email.com | +44-20-555-0182\nFRM-certified risk professional with 8 years of quantitative risk management at Tier-1 banks.\nHead of Market Risk | HSBC | 03/2020 - Present\nLead VaR model development and stress testing frameworks (Basel III / FRTB).\nManage regulatory reporting to PRA and EBA.\nSenior Credit Risk Analyst | Barclays | 01/2016 - 02/2020\nBuild credit risk models using Python/R. Develop IFRS 9 Expected Credit Loss (ECL) models.\nMSc Financial Mathematics | Imperial College London | 2015\nSkills: Risk Management, Credit Risk, Market Risk, VaR, Stress Testing, Basel III, Regulatory Reporting, Python, R, SQL, Financial Modeling, FRM"},
    {"name": "Fatima Al-Rashidi", "email": "fatima.rashidi@email.com", "phone": "+971-50-555-0183", "education": "Bachelor", "experience_years": 4.0, "skills": ["aml", "kyc", "compliance", "regulatory compliance", "risk management", "financial analysis", "excel", "sql"], "raw_text": "Fatima Al-Rashidi\nfatima.rashidi@email.com | +971-50-555-0183\nCompliance and AML professional with 4 years of experience in banking.\nAML Compliance Officer | Emirates NBD | 08/2022 - Present\nManage transaction monitoring, suspicious activity reporting, and KYC onboarding.\nCompliance Analyst | Abu Dhabi Islamic Bank | 06/2020 - 07/2022\nBachelor of Finance | American University of Sharjah | 2020\nSkills: AML, KYC, Anti-Money Laundering, Compliance, Regulatory Compliance, Risk Management, Financial Analysis, Excel, SQL"},
    {"name": "Oliver Thornton", "email": "oliver.thornton@email.com", "phone": "+1-312-555-0184", "education": "Bachelor", "experience_years": 3.0, "skills": ["financial modeling", "budgeting", "forecasting", "excel", "sap fico", "financial reporting", "variance analysis", "gaap", "powerpoint"], "raw_text": "Oliver Thornton\noliver.thornton@email.com | +1-312-555-0184\nFinancial Analyst with 3 years of FP&A experience in manufacturing.\nFinancial Analyst FP&A | Caterpillar Inc. | 07/2021 - Present\nBuild annual budgets and rolling forecasts for $500M revenue business unit.\nPerform variance analysis comparing actuals vs plan.\nJunior Financial Analyst | Abbott Laboratories | 06/2020 - 06/2021\nBachelor of Accounting | University of Illinois | 2020\nSkills: Financial Modeling, Budgeting, Forecasting, Excel, SAP FICO, Financial Reporting, Variance Analysis, GAAP, PowerPoint"},
    {"name": "Yuki Tanaka", "email": "yuki.tanaka@email.com", "phone": "+81-3-555-0185", "education": "Bachelor", "experience_years": 5.0, "skills": ["treasury management", "cash management", "fx hedging", "financial modeling", "excel", "sap", "forecasting", "financial analysis"], "raw_text": "Yuki Tanaka\nyuki.tanaka@email.com | +81-3-555-0185\nTreasury professional with 5 years of experience managing cash and FX in multinational corporations.\nTreasury Manager | Sony Corporation | 04/2021 - Present\nManage $2B+ global cash positions and short-term investment portfolio.\nExecute FX hedging strategies across 15 currencies. Lead SAP Treasury implementation.\nBachelor of Finance | Keio University | 2019\nSkills: Treasury Management, Cash Management, FX Hedging, Financial Modeling, Excel, SAP, Forecasting"},
    # ── HEALTHCARE ────────────────────────────────────────────────────────────
    {"name": "Dr. Emma Hartley", "email": "emma.hartley@email.com", "phone": "+1-617-555-0186", "education": "PhD", "experience_years": 7.0, "skills": ["clinical research", "clinical trials", "biostatistics", "r", "python", "clinical data management", "redcap", "gcp", "fda regulations", "medical writing"], "raw_text": "Dr. Emma Hartley\nemma.hartley@email.com | +1-617-555-0186\nPhD Biostatistician with 7 years in pharmaceutical and CRO environments.\nPrincipal Biostatistician | Pfizer | 09/2020 - Present\nLead statistical analysis for Phase II/III oncology trials (NDA/BLA submissions).\nDevelop SAP, TLF shells, CDISC datasets. Program in R and manage REDCap.\nPhD Biostatistics | Harvard School of Public Health | 2017\nSkills: Clinical Research, Clinical Trials, Biostatistics, R, Python, Clinical Data Management, REDCap, GCP, FDA Regulations, Medical Writing"},
    {"name": "James Okafor", "email": "james.okafor@email.com", "phone": "+1-713-555-0187", "education": "Bachelor", "experience_years": 4.0, "skills": ["emr", "ehr", "epic", "hl7", "fhir", "hipaa", "healthcare interoperability", "sql", "project management"], "raw_text": "James Okafor\njames.okafor@email.com | +1-713-555-0187\nHealthcare IT professional with 4 years of Epic EHR implementation experience.\nEpic Implementation Consultant | Texas Medical Center | 03/2022 - Present\nLead Epic Ambulatory go-live for 800-physician practice.\nConfigure HL7 interfaces and FHIR API integrations. Ensure HIPAA compliance.\nBachelor of Health Information Management | University of Houston | 2020\nSkills: EMR, EHR, Epic, HL7, FHIR, HIPAA, Healthcare Interoperability, SQL, Project Management"},
    {"name": "Natalie Dupont", "email": "natalie.dupont@email.com", "phone": "+33-1-555-0188", "education": "Master", "experience_years": 5.0, "skills": ["pharmacovigilance", "drug safety", "adverse event reporting", "fda regulations", "gcp", "medical writing", "regulatory submissions", "clinical research"], "raw_text": "Natalie Dupont\nnatalie.dupont@email.com | +33-1-555-0188\nPharmacovigilance specialist with 5 years in global drug safety.\nSenior PV Specialist | Sanofi | 01/2021 - Present\nProcess and assess serious adverse event (SAE) reports per ICH E2 guidelines.\nPrepare Periodic Safety Update Reports (PSURs) for 6 marketed products.\nMSc Pharmacology | Universite Paris-Saclay | 2019\nSkills: Pharmacovigilance, Drug Safety, Adverse Event Reporting, FDA Regulations, GCP, Medical Writing, Regulatory Submissions"},
    {"name": "Priya Subramaniam", "email": "priya.subramaniam@email.com", "phone": "+1-617-555-0189", "education": "Master", "experience_years": 5.0, "skills": ["machine learning", "python", "r", "healthcare analytics", "hl7", "fhir", "nlp", "biostatistics", "sql", "data science"], "raw_text": "Priya Subramaniam\npriya.subramaniam@email.com | +1-617-555-0189\nHealthcare data scientist with 5 years applying ML and NLP to clinical data.\nSenior Data Scientist | Mass General Brigham | 06/2021 - Present\nDevelop sepsis early warning models using EHR time-series data (AUC 0.92).\nApply NLP to clinical notes for ICD-10 coding automation.\nMSc Biomedical Informatics | Harvard Medical School | 2019\nSkills: Machine Learning, Python, R, Healthcare Analytics, HL7, FHIR, NLP, Biostatistics, SQL, Data Science, ICD-10"},
    {"name": "Amir Khalil", "email": "amir.khalil@email.com", "phone": "+49-89-555-0212", "education": "Master", "experience_years": 6.0, "skills": ["hospital administration", "healthcare operations", "project management", "lean manufacturing", "six sigma", "budgeting", "stakeholder management"], "raw_text": "Amir Khalil\namir.khalil@email.com | +49-89-555-0212\nHealthcare operations manager with 6 years of experience in hospital administration.\nOperations Director | Charite Hospital | 03/2020 - Present\nOversee daily operations for 500-bed teaching hospital.\nLead Lean Six Sigma process improvement projects reducing patient wait time by 35%.\nManage annual budget of EUR 80M and coordinate with 12 clinical departments.\nMSc Health Management | Technical University Munich | 2018\nSkills: Hospital Administration, Healthcare Operations, Project Management, Lean Manufacturing, Six Sigma, Budgeting, Stakeholder Management"},
    # ── DIGITAL MARKETING ─────────────────────────────────────────────────────
    {"name": "Isabella Romano", "email": "isabella.romano@email.com", "phone": "+39-02-555-0190", "education": "Bachelor", "experience_years": 6.0, "skills": ["digital marketing", "seo", "sem", "google ads", "meta ads", "google analytics", "ga4", "hubspot", "email marketing", "a/b testing", "content marketing"], "raw_text": "Isabella Romano\nisabella.romano@email.com | +39-02-555-0190\nDigital marketing leader with 6 years scaling performance marketing programs.\nHead of Digital Marketing | Zalando Italy | 04/2022 - Present\nManage EUR 5M annual paid media budget across Google Ads, Meta Ads, and programmatic.\nLead SEO strategy driving 120% organic traffic growth. Implement GA4 migration.\nBachelor of Marketing | Bocconi University | 2018\nSkills: Digital Marketing, SEO, SEM, PPC, Google Ads, Meta Ads, Google Analytics, GA4, HubSpot, Email Marketing, A/B Testing, Content Marketing, Performance Marketing"},
    {"name": "Carlos Mendez", "email": "carlos.mendez@email.com", "phone": "+34-91-555-0191", "education": "Bachelor", "experience_years": 4.0, "skills": ["seo", "content marketing", "copywriting", "ahrefs", "semrush", "google analytics", "content strategy", "a/b testing", "social media marketing"], "raw_text": "Carlos Mendez\ncarlos.mendez@email.com | +34-91-555-0191\nSEO and content specialist with 4 years growing organic search presence.\nSEO Manager | Idealista | 06/2022 - Present\nGrew organic sessions by 180% through technical SEO and content hub strategy.\nConduct keyword research using Ahrefs and SEMrush. Implement Core Web Vitals optimisation.\nBachelor of Journalism | Universidad Complutense de Madrid | 2020\nSkills: SEO, Content Marketing, Copywriting, Ahrefs, SEMrush, Google Analytics, Content Strategy, A/B Testing, Social Media Marketing"},
    {"name": "Aisha Nwosu", "email": "aisha.nwosu@email.com", "phone": "+234-80-555-0192", "education": "Bachelor", "experience_years": 3.0, "skills": ["brand management", "social media marketing", "content marketing", "canva", "adobe creative suite", "community management", "copywriting", "influencer marketing", "google analytics"], "raw_text": "Aisha Nwosu\naisha.nwosu@email.com | +234-80-555-0192\nCreative brand and social media professional with 3 years building engaged communities.\nBrand & Social Media Manager | Jumia | 08/2023 - Present\nManage brand identity across Instagram (500K followers), LinkedIn, TikTok.\nExecute influencer marketing campaigns with 8x ROAS.\nBachelor of Mass Communication | University of Lagos | 2021\nSkills: Brand Management, Social Media Marketing, Content Marketing, Canva, Adobe Creative Suite, Community Management, Copywriting, Influencer Marketing, Google Analytics"},
    {"name": "Thomas Mueller", "email": "thomas.mueller@email.com", "phone": "+49-89-555-0193", "education": "Master", "experience_years": 5.0, "skills": ["crm", "hubspot", "email marketing", "marketing automation", "salesforce", "customer lifecycle", "sql", "a/b testing", "data analysis"], "raw_text": "Thomas Mueller\nthomas.mueller@email.com | +49-89-555-0193\nCRM and marketing automation specialist with 5 years in B2B SaaS and fintech.\nCRM Manager | N26 | 07/2022 - Present\nManage 40+ automated customer journeys across HubSpot reaching 2M+ users.\nLead A/B testing program generating EUR 3.2M additional annual revenue.\nMSc Marketing | Ludwig Maximilian University Munich | 2019\nSkills: CRM, HubSpot, Email Marketing, Marketing Automation, Salesforce, Customer Lifecycle, SQL, A/B Testing, Data Analysis"},
    {"name": "Laura Chen", "email": "laura.chen@email.com", "phone": "+1-415-555-0213", "education": "Bachelor", "experience_years": 3.0, "skills": ["performance marketing", "ppc", "google ads", "meta ads", "a/b testing", "google analytics", "sql", "tableau", "conversion rate optimization"], "raw_text": "Laura Chen\nlaura.chen@email.com | +1-415-555-0213\nPerformance marketing analyst with 3 years optimizing paid media campaigns.\nPerformance Marketing Analyst | Airbnb | 01/2023 - Present\nManage $8M annual paid search budget across Google Ads, Meta, and LinkedIn.\nBuild attribution models and conduct A/B tests reducing CPA by 22%.\nBachelor of Business Administration | UC Berkeley | 2022\nSkills: Performance Marketing, PPC, Google Ads, Meta Ads, A/B Testing, Google Analytics, SQL, Tableau, Conversion Rate Optimization"},
    # ── LEGAL ─────────────────────────────────────────────────────────────────
    {"name": "Victoria Chambers", "email": "victoria.chambers@email.com", "phone": "+44-20-555-0194", "education": "Master", "experience_years": 8.0, "skills": ["corporate law", "contract drafting", "contract negotiation", "merger & acquisition", "legal research", "legal writing", "compliance", "due diligence"], "raw_text": "Victoria Chambers\nvictoria.chambers@email.com | +44-20-555-0194\nQualified solicitor with 8 years in corporate law and M&A at Magic Circle firm.\nSenior Associate | Freshfields Bruckhaus Deringer | 09/2019 - Present\nLead legal execution on 20+ M&A transactions (deal values GBP 50M to 3B).\nDraft and negotiate SPAs, JVAs, and SHA agreements.\nLLM Corporate Law | London School of Economics | 2016\nSkills: Corporate Law, Contract Drafting, Contract Negotiation, Merger & Acquisition, Legal Research, Legal Writing, Compliance, Due Diligence"},
    {"name": "Rafael Souza", "email": "rafael.souza@email.com", "phone": "+55-11-555-0195", "education": "Bachelor", "experience_years": 4.0, "skills": ["data privacy", "gdpr", "ccpa", "regulatory compliance", "legal research", "legal writing", "compliance", "contract drafting"], "raw_text": "Rafael Souza\nrafael.souza@email.com | +55-11-555-0195\nData privacy lawyer with 4 years implementing GDPR, LGPD, and CCPA compliance.\nData Privacy Counsel | iFood | 03/2022 - Present\nDeveloped LGPD/GDPR compliance framework covering 45M user records.\nConducted DPIAs, managed data subject requests and DPAs with 200+ vendors.\nBachelor of Law | Universidade de Sao Paulo | 2019\nSkills: Data Privacy, GDPR, CCPA, Regulatory Compliance, Legal Research, Legal Writing, Compliance, Contract Drafting"},
    {"name": "Mei-Ling Chang", "email": "meiling.chang@email.com", "phone": "+886-2-555-0196", "education": "Master", "experience_years": 6.0, "skills": ["intellectual property", "patent law", "trademark", "copyright", "contract drafting", "legal research", "licensing", "compliance"], "raw_text": "Mei-Ling Chang\nmeiling.chang@email.com | +886-2-555-0196\nIP attorney with 6 years in patent prosecution and technology licensing.\nSenior IP Counsel | TSMC | 06/2020 - Present\nManage 2000+ patent portfolio across US, EP, CN, JP jurisdictions.\nNegotiate and draft technology licensing agreements.\nLLM Intellectual Property | UC Berkeley | 2018\nSkills: Intellectual Property, Patent Law, Trademark, Copyright, Contract Drafting, Legal Research, Licensing"},
    # ── ENGINEERING ───────────────────────────────────────────────────────────
    {"name": "Henrik Larsson", "email": "henrik.larsson@email.com", "phone": "+46-8-555-0197", "education": "Master", "experience_years": 9.0, "skills": ["solidworks", "catia", "finite element analysis", "ansys", "mechanical design", "autocad", "lean manufacturing", "fmea", "quality management"], "raw_text": "Henrik Larsson\nhenrik.larsson@email.com | +46-8-555-0197\nLead mechanical design engineer with 9 years in automotive and heavy machinery.\nLead Mechanical Engineer | Volvo Cars | 03/2019 - Present\nLead structural design of BEV battery enclosures in SolidWorks and CATIA V5.\nPerform non-linear FEA crash and durability simulations in ANSYS.\nMSc Mechanical Engineering | KTH Royal Institute of Technology | 2015\nSkills: SolidWorks, CATIA, Finite Element Analysis, ANSYS, Mechanical Design, AutoCAD, Lean Manufacturing, FMEA, Quality Management"},
    {"name": "Amara Diallo", "email": "amara.diallo@email.com", "phone": "+33-1-555-0198", "education": "Bachelor", "experience_years": 5.0, "skills": ["civil engineering", "structural analysis", "autocad", "revit", "bim", "construction management", "project scheduling", "ms project"], "raw_text": "Amara Diallo\namara.diallo@email.com | +33-1-555-0198\nStructural engineer with 5 years designing commercial and infrastructure projects.\nStructural Engineer | Bouygues Construction | 09/2021 - Present\nDesign reinforced concrete and steel structures for commercial buildings.\nDevelop Revit BIM models and coordinate with MEP and architectural teams.\nBachelor of Civil Engineering | Ecole des Ponts ParisTech | 2019\nSkills: Civil Engineering, Structural Analysis, AutoCAD, Revit, BIM, Construction Management, Project Scheduling, MS Project"},
    {"name": "Sanjay Patel", "email": "sanjay.patel@email.com", "phone": "+91-98-555-0199", "education": "Bachelor", "experience_years": 7.0, "skills": ["electrical engineering", "plc programming", "scada", "instrumentation", "control systems", "autocad", "quality management", "lean manufacturing"], "raw_text": "Sanjay Patel\nsanjay.patel@email.com | +91-98-555-0199\nElectrical and instrumentation engineer with 7 years in oil & gas.\nE&I Senior Engineer | Reliance Industries | 04/2020 - Present\nDesign instrument loop diagrams, P&IDs, and cause-and-effect matrices.\nProgram Siemens S7-1500 PLCs and Honeywell DCS systems.\nBachelor of Electrical Engineering | IIT Bombay | 2017\nSkills: Electrical Engineering, PLC Programming, SCADA, Instrumentation, Control Systems, AutoCAD, Quality Management"},
    {"name": "Laura Bianchi", "email": "laura.bianchi@email.com", "phone": "+39-02-555-0200", "education": "Master", "experience_years": 6.0, "skills": ["lean manufacturing", "six sigma", "quality management", "fmea", "root cause analysis", "process improvement", "autocad", "iso 9001"], "raw_text": "Laura Bianchi\nlaura.bianchi@email.com | +39-02-555-0200\nLean Six Sigma Black Belt with 6 years driving process improvement in automotive.\nLean Manufacturing Manager | Ferrari S.p.A. | 01/2022 - Present\nLead Kaizen events and VSM across 5 production lines.\nImplement SPC reducing defect rate by 40%. Lead IATF 16949 audit preparation.\nMSc Industrial Engineering | Politecnico di Milano | 2018\nSkills: Lean Manufacturing, Six Sigma, Quality Management, FMEA, Root Cause Analysis, Process Improvement, AutoCAD, ISO 9001"},
    {"name": "Chen Wei", "email": "chen.wei@email.com", "phone": "+86-21-555-0214", "education": "Bachelor", "experience_years": 4.0, "skills": ["mechanical design", "solidworks", "autocad", "finite element analysis", "quality management", "lean manufacturing", "3d printing", "cam", "cnc"], "raw_text": "Chen Wei\nchen.wei@email.com | +86-21-555-0214\nMechanical engineer with 4 years in consumer electronics product design.\nMechanical Design Engineer | Huawei Technologies | 06/2020 - Present\nDesign enclosures and thermal management for flagship smartphone product line.\nUse SolidWorks and AutoCAD for 3D modeling and DFM analysis.\nBachelor of Mechanical Engineering | Shanghai Jiao Tong University | 2020\nSkills: Mechanical Design, SolidWorks, AutoCAD, Finite Element Analysis, Quality Management, Lean Manufacturing, 3D Printing, CAM, CNC"},
    # ── HUMAN RESOURCES ──────────────────────────────────────────────────────
    {"name": "Sarah Okonkwo", "email": "sarah.okonkwo@email.com", "phone": "+44-20-555-0201", "education": "Master", "experience_years": 7.0, "skills": ["talent acquisition", "performance management", "employee relations", "change management", "hr analytics", "workday", "employment law", "organizational development"], "raw_text": "Sarah Okonkwo\nsarah.okonkwo@email.com | +44-20-555-0201\nStrategic HR Business Partner with 7 years in financial services and technology. CIPD Level 7 qualified.\nSenior HR Business Partner | Barclays | 09/2020 - Present\nPartner with 3 business units (1500 employees) on all people matters.\nLead organizational design, manage employee relations cases, drive diversity & inclusion.\nMSc Human Resource Management | London School of Economics | 2017\nSkills: Talent Acquisition, Performance Management, Employee Relations, Change Management, HR Analytics, Workday, Employment Law, Organizational Development"},
    {"name": "Daniel Kim", "email": "daniel.kim@email.com", "phone": "+1-415-555-0202", "education": "Bachelor", "experience_years": 4.0, "skills": ["talent acquisition", "recruitment", "linkedin recruiter", "sourcing", "hris", "hr analytics", "onboarding", "stakeholder management"], "raw_text": "Daniel Kim\ndaniel.kim@email.com | +1-415-555-0202\nTalent acquisition professional with 4 years recruiting technical and business talent.\nSenior Talent Acquisition Partner | Stripe | 01/2023 - Present\nFull-cycle recruitment for engineering, product, and go-to-market roles.\nSource passive candidates using LinkedIn Recruiter and Boolean search.\nBachelor of Psychology | UC San Diego | 2020\nSkills: Talent Acquisition, Recruitment, LinkedIn Recruiter, Sourcing, HRIS, HR Analytics, Onboarding, Stakeholder Management"},
    {"name": "Charlotte Dubois", "email": "charlotte.dubois@email.com", "phone": "+33-1-555-0203", "education": "Master", "experience_years": 5.0, "skills": ["learning & development", "instructional design", "e-learning", "articulate storyline", "lms", "moodle", "training delivery", "content creation", "facilitation", "hr analytics"], "raw_text": "Charlotte Dubois\ncharlotte.dubois@email.com | +33-1-555-0203\nL&D specialist with 5 years designing digital and blended learning for global organisations.\nL&D Specialist | L'Oreal | 04/2022 - Present\nDesign leadership development programs for 500+ managers globally.\nBuild SCORM-compliant e-learning in Articulate Storyline and Rise.\nMSc Organizational Psychology | Sciences Po Paris | 2019\nSkills: Learning & Development, Instructional Design, E-Learning, Articulate Storyline, LMS, Moodle, Training Delivery, Content Creation, Facilitation, HR Analytics, Adult Learning Theory"},
    {"name": "Marcus Thompson", "email": "marcus.thompson@email.com", "phone": "+1-312-555-0215", "education": "Bachelor", "experience_years": 4.0, "skills": ["compensation & benefits", "hr analytics", "excel", "financial modeling", "workday", "hris", "stakeholder management"], "raw_text": "Marcus Thompson\nmarcus.thompson@email.com | +1-312-555-0215\nCompensation and benefits analyst with 4 years of total rewards experience.\nSenior Comp & Benefits Analyst | McDonald's Corporation | 03/2022 - Present\nConduct market pay benchmarking using Mercer and Willis Towers Watson surveys.\nMaintain job architecture for 15,000+ global employees in Workday.\nBachelor of Human Resource Management | Michigan State University | 2021\nSkills: Compensation & Benefits, HR Analytics, Excel, Financial Modeling, Workday, HRIS, Stakeholder Management"},
    # ── SUPPLY CHAIN ──────────────────────────────────────────────────────────
    {"name": "Ahmed Hassan", "email": "ahmed.hassan@email.com", "phone": "+20-2-555-0204", "education": "Bachelor", "experience_years": 5.0, "skills": ["supply chain management", "demand planning", "s&op", "inventory management", "sap scm", "sql", "excel", "data analysis", "procurement"], "raw_text": "Ahmed Hassan\nahmed.hassan@email.com | +20-2-555-0204\nSupply chain analyst with 5 years optimising demand planning and inventory across MENA.\nSupply Chain Analyst | Unilever Egypt | 06/2021 - Present\nLead S&OP process for 3 product categories (EUR 200M revenue).\nBuild demand forecasting models reducing forecast error by 18%.\nBachelor of Industrial Engineering | Cairo University | 2019\nSkills: Supply Chain Management, Demand Planning, S&OP, Inventory Management, SAP SCM, SQL, Excel, Data Analysis, Procurement"},
    {"name": "Anna Kowalski", "email": "anna.kowalski@email.com", "phone": "+48-22-555-0205", "education": "Master", "experience_years": 8.0, "skills": ["procurement", "strategic sourcing", "vendor management", "category management", "contract negotiation", "sap", "rfq", "supply chain management", "compliance"], "raw_text": "Anna Kowalski\nanna.kowalski@email.com | +48-22-555-0205\nProcurement director with 8 years building strategic sourcing functions in CEE.\nProcurement Manager | KGHM Polska Miedz | 03/2019 - Present\nLead indirect procurement for $150M annual spend across 12 categories.\nDeliver 8-12% cost savings annually through strategic sourcing.\nMSc Supply Chain Management | SGH Warsaw School of Economics | 2016\nSkills: Procurement, Strategic Sourcing, Vendor Management, Category Management, Contract Negotiation, SAP, RFQ, Supply Chain Management, Compliance"},
    {"name": "Lucas Ferreira", "email": "lucas.ferreira@email.com", "phone": "+55-21-555-0206", "education": "Bachelor", "experience_years": 6.0, "skills": ["logistics", "warehousing", "inventory management", "3pl", "import/export", "customs", "supply chain management", "vendor management", "lean manufacturing"], "raw_text": "Lucas Ferreira\nlucas.ferreira@email.com | +55-21-555-0206\nLogistics manager with 6 years managing complex distribution networks in Brazil.\nLogistics Manager | Magazine Luiza | 08/2020 - Present\nManage 4 distribution centers (2M+ daily shipments).\nOversee 3PL contracts totaling R$120M annually.\nBachelor of Logistics Engineering | PUC-Rio | 2018\nSkills: Logistics, Warehousing, Inventory Management, 3PL, Import/Export, Customs, Supply Chain Management, Vendor Management, Lean Manufacturing"},
    {"name": "Nadia Al-Farsi", "email": "nadia.alfarsi@email.com", "phone": "+971-55-555-0216", "education": "Master", "experience_years": 4.0, "skills": ["supply chain management", "procurement", "vendor management", "sap scm", "demand planning", "excel", "data analysis", "project management"], "raw_text": "Nadia Al-Farsi\nnadia.alfarsi@email.com | +971-55-555-0216\nSupply chain professional with 4 years in retail and FMCG sectors in the Gulf.\nSupply Chain Manager | Majid Al Futtaim | 05/2022 - Present\nManage procurement and vendor relationships for 300+ hypermarket SKUs.\nOptimize SAP SCM demand planning module to reduce out-of-stock by 25%.\nMSc Supply Chain Management | University of Birmingham | 2020\nSkills: Supply Chain Management, Procurement, Vendor Management, SAP SCM, Demand Planning, Excel, Data Analysis, Project Management"},
    # ── SALES & BUSINESS DEVELOPMENT ──────────────────────────────────────────
    {"name": "James Harrington", "email": "james.harrington@email.com", "phone": "+1-646-555-0207", "education": "Bachelor", "experience_years": 10.0, "skills": ["b2b sales", "enterprise sales", "sales management", "salesforce", "pipeline management", "negotiation", "sales forecasting", "crm", "leadership"], "raw_text": "James Harrington\njames.harrington@email.com | +1-646-555-0207\nEnterprise sales leader with 10 years building and scaling B2B SaaS sales teams.\nVP of Sales | Salesforce | 07/2020 - Present\nLead team of 25 enterprise AEs covering Fortune 1000 accounts.\nExceed annual quota of $40M ARR by 115% for 3 consecutive years.\nBachelor of Business Administration | University of Michigan | 2014\nSkills: B2B Sales, Enterprise Sales, Sales Management, Salesforce, Pipeline Management, Negotiation, Sales Forecasting, CRM, Leadership, Revenue Operations"},
    {"name": "Ingrid Svensson", "email": "ingrid.svensson@email.com", "phone": "+46-8-555-0208", "education": "Bachelor", "experience_years": 5.0, "skills": ["business development", "b2b sales", "market research", "negotiation", "crm", "strategic planning", "stakeholder management", "salesforce", "partnership development"], "raw_text": "Ingrid Svensson\ningrid.svensson@email.com | +46-8-555-0208\nBusiness development professional with 5 years building strategic partnerships for Nordic tech.\nBusiness Development Manager | Klarna | 01/2022 - Present\nClose 30+ merchant partnerships per year across banks and e-commerce platforms.\nBuild go-to-market strategy for DACH and UK market expansion.\nBachelor of International Business | Stockholm School of Economics | 2019\nSkills: Business Development, B2B Sales, Market Research, Negotiation, CRM, Strategic Planning, Stakeholder Management, Salesforce, Partnership Development"},
    {"name": "Priya Krishnamurthy", "email": "priya.krishnamurthy@email.com", "phone": "+1-415-555-0209", "education": "Bachelor", "experience_years": 4.0, "skills": ["customer success", "account management", "salesforce", "crm", "upselling", "stakeholder management", "client relationship management", "data analysis"], "raw_text": "Priya Krishnamurthy\npriya.krishnamurthy@email.com | +1-415-555-0209\nCustomer Success Manager with 4 years driving adoption and retention for enterprise SaaS.\nSenior Customer Success Manager | Snowflake | 03/2022 - Present\nOwn portfolio of 15 enterprise accounts ($8M ARR).\nDrive NPS from 42 to 71 through structured success programs and QBRs.\nBachelor of Business Administration | UC Berkeley | 2020\nSkills: Customer Success, Account Management, Salesforce, CRM, Upselling, Stakeholder Management, Client Relationship Management, Data Analysis"},
    {"name": "David Park", "email": "david.park@email.com", "phone": "+82-2-555-0217", "education": "Bachelor", "experience_years": 7.0, "skills": ["b2b sales", "enterprise sales", "salesforce", "pipeline management", "negotiation", "crm", "account management", "sales forecasting"], "raw_text": "David Park\ndavid.park@email.com | +82-2-555-0217\nEnterprise sales professional with 7 years in SaaS and technology solutions.\nEnterprise Account Executive | Oracle Korea | 04/2020 - Present\nManage 25-account enterprise portfolio across financial services and manufacturing.\nAchieve 130% quota attainment for 3 consecutive years.\nBachelor of Business | Korea University | 2017\nSkills: B2B Sales, Enterprise Sales, Salesforce, Pipeline Management, Negotiation, CRM, Account Management, Sales Forecasting"},
    # ── EDUCATION & TRAINING ──────────────────────────────────────────────────
    {"name": "Rachel Foster", "email": "rachel.foster@email.com", "phone": "+1-512-555-0210", "education": "Master", "experience_years": 6.0, "skills": ["instructional design", "e-learning", "articulate storyline", "scorm", "lms", "moodle", "curriculum development", "adult learning theory", "content creation", "facilitation"], "raw_text": "Rachel Foster\nrachel.foster@email.com | +1-512-555-0210\nInstructional designer with 6 years creating award-winning e-learning solutions.\nSenior Instructional Designer | Dell Technologies | 04/2021 - Present\nDesign SCORM-compliant courses in Articulate Storyline 360 and Rise.\nManage Cornerstone LMS for 100K+ employees globally.\nMSc Instructional Technology | University of Texas at Austin | 2018\nSkills: Instructional Design, E-Learning, Articulate Storyline, SCORM, LMS, Moodle, Curriculum Development, Adult Learning Theory, Content Creation, Facilitation, ADDIE"},
    {"name": "Michael Adeyemi", "email": "michael.adeyemi@email.com", "phone": "+234-80-555-0211", "education": "Master", "experience_years": 8.0, "skills": ["training delivery", "learning & development", "instructional design", "lms", "facilitation", "coaching", "stakeholder management", "hr analytics", "curriculum development"], "raw_text": "Michael Adeyemi\nmichael.adeyemi@email.com | +234-80-555-0211\nL&D leader with 8 years building corporate universities in banking and telecommunications.\nHead of L&D | Zenith Bank | 01/2020 - Present\nLead team of 12 trainers and instructional designers.\nDesign leadership academy for 300+ senior managers. Manage SuccessFactors LMS for 8000 employees.\nMSc Human Resource Development | University of Ibadan | 2016\nSkills: Training Delivery, Learning & Development, Instructional Design, LMS, Moodle, Facilitation, Coaching, Stakeholder Management, HR Analytics, Curriculum Development"},
]


def main():
    db = SessionLocal()
    try:
        existing_job_titles = {j.title for j in db.query(JobPosting).all()}
        existing_emails = {c.email for c in db.query(Candidate).all()}

        added_jobs = 0
        for jd in NEW_JOBS:
            if jd["title"] not in existing_job_titles:
                db.add(JobPosting(**jd))
                existing_job_titles.add(jd["title"])
                added_jobs += 1

        db.commit()
        print(f"[OK] Added {added_jobs} new job postings")

        added_candidates = 0
        for cd in NEW_CANDIDATES:
            if cd["email"] not in existing_emails:
                skills = cd.pop("skills")
                c = Candidate(**cd)
                db.add(c)
                db.flush()
                for skill in skills:
                    db.add(Skill(candidate_id=c.id, skill_name=skill))
                cd["skills"] = skills  # restore for safety
                existing_emails.add(cd["email"])
                added_candidates += 1

        db.commit()
        print(f"[OK] Added {added_candidates} new candidates")

        total_jobs = db.query(JobPosting).count()
        total_candidates = db.query(Candidate).count()
        print(f"[TOTAL] {total_jobs} jobs, {total_candidates} candidates")

    finally:
        db.close()


if __name__ == "__main__":
    main()
